In [1]:
import numpy as np

# **BASICS**

In [11]:
# 1d array
a=np.array([1,2,3], dtype='int16')  #dtype by default is int 64
a

array([1, 2, 3], dtype=int16)

In [5]:
#2d array 
b=np.array([[1.0,2.0,3.0],[1.1,1.2,1.3]])
b

array([[1. , 2. , 3. ],
       [1.1, 1.2, 1.3]])

In [7]:
#get dimension
b.ndim

2

In [9]:
#get shape
b.shape

(2, 3)

In [12]:
#get type
a.dtype

dtype('int16')

In [14]:
#get size 
a.itemsize #gives the bytes(byte consists of 8 bits)
a.size #gives total number of elements ..its 3 for a)

3

In [17]:
#total size
a.size * a.itemsize 
#or we can just use number bytes
a.nbytes

6

# **Access/Change specific elements, rows, columns etc**

In [22]:
arr=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]], dtype='int32' )
arr

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]], dtype=int32)

In [23]:
#get element -- notaion used is [ rows, cols ]
#get 13
arr[1,5]

np.int32(13)

In [24]:
# getting rows  [row, :] --- used the basic slice syntax
arr[1, :]

array([ 8,  9, 10, 11, 12, 13, 14], dtype=int32)

In [25]:
#Get a specific col
arr[:, 0]

array([1, 8], dtype=int32)

In [26]:
# accessing element -- fancier -- [startindex:endindex(non-inclusive):stepsize]
arr[0, 1:6:2]

array([2, 4, 6], dtype=int32)

In [29]:
#change element
arr[1,5]=20
arr

arr[:,2]=5
print(arr)

arr[:,2]=[1,2]
print(arr)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [31]:
# 3D array
a3d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a3d)
#accessing element in a 3d arr -- work from outside in
#accessing 4 which is 2nd element in the fisrt row and 2nd col
a3d[0,1,1]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


np.int64(4)

In [33]:
#replace

a3d[:,1,:]=[[9,9],[8,8]]
a3d

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# **Initializing different types of arrays**

In [38]:
# All 0s matrix
np.zeros(5)
np.zeros((2,3))
np.zeros((2,3,3))


array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [41]:
# All ones matrix
np.ones(4)
np.ones((2,3), dtype='int32')


array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [43]:
# Any other numbers -- syntax (shape, number u want to fill the matrix with)
np.full(5,99)
np.full((2,2),10)

array([[10, 10],
       [10, 10]])

In [46]:
# full_like
np.full_like(arr, 10)
np.full(arr.shape, 2)

array([[2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2]])

In [49]:
# Random Ddecimal numbers
np.random.rand(2,2,3)

#random number--if u want to get a shape of exisiting arr
np.random.random_sample(arr.shape)


array([[0.50663497, 0.98941819, 0.94990496, 0.95304843, 0.41636029,
        0.58126712, 0.16599986],
       [0.03063309, 0.73396226, 0.75381967, 0.50057401, 0.32254156,
        0.89165338, 0.51425976]])

In [52]:
# random integer values -- (the numbers to be included starts from zero and ending u specify, shape-->use size=())
np.random.randint(10, size=(2,2))
np.random.randint(-2,10, size=(3,3))

array([[ 5,  8,  1],
       [ 7, -2, -2],
       [ 4,  7,  1]])

In [53]:
# identity matrix-- needs one argument cause its a sqare matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
 # repeat an array
a= np.array([[1,2,3]])
r1= np.repeat(a, 3, axis=0)# 0 axis ..repeat across cols
r1


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [58]:
#quess-- make the following array using the concepts above
# 1 1 1 1 1 
# 1 0 0 0 1
# 1 0 9 0 1
# 1 0 0 0 1
# 1 1 1 1 1

In [64]:
output=np.ones((5,5) ,dtype='int16')
output
output[1:4, 1:4]= 0
output
output[2,2]=9
print(output)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


# **Mathematics**

In [74]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [67]:
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)
print(a % 2)

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[1 0 1 0]


In [71]:
# take the sin values
np.sin(a)
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [76]:
# sqrt , power, log , exponential
# print(a ** 2)#square
print(np.log10(a))
print(np.sqrt(a))
print(np.exp(a))

[0.         0.30103    0.47712125 0.60205999]
[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]


### **Linear Algebra**

In [78]:
a=np.ones((2,3))
print(a)

b= np.full((3,2), 2)
print(b)

np.matmul(a,b) # matrix multiplication


[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [79]:
# find the determinant

c=np.identity(3) #id mat has det=1
np.linalg.det(c)

np.float64(1.0)

### **Statistics**

In [81]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
np.min(stats ,axis=0)

array([1, 2, 3])

In [85]:
np.max(stats,axis=1)

array([3, 6])

In [87]:
np.sum(stats, axis=1)

array([ 6, 15])

### **Reorganising arrays**

In [90]:
#reshape

before = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]], dtype='int32' )
print(before)

after = before.reshape((7,2))
print(after)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]]


In [92]:
# vertically statcking matrices -- cols must be the same for both
v1=np.array([1,2,3])
v2=np.array([4,5,6])

np.vstack([v1,v2,v1,v2,v2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

In [96]:
# horizontal stack-- rows must be the same for both

h1=np.ones((2,3))
h2=np.zeros((2,4))

np.hstack([h2,h1])

array([[0., 0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1.]])

# **Miscellaneous**

In [101]:
# load data from file
filedata = np.genfromtxt("data.txt", delimiter=',')
filedata
filedata = filedata.astype('int32')
filedata

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,   1,  11,  12,
        13,  14,  15,  16,  18,  19, 100,  20,  30,  40,  50,   5,  98,
       200], dtype=int32)

##### **Advanced indexing and boolean masking**

In [103]:
filedata[filedata>50]

array([100,  98, 200], dtype=int32)

In [107]:
# we can index using list in numpy
a = np.arange(20,30,1) # range(start, stop(non-inclusive), step)
print(a)

a[[1,3,5]]
 

[20 21 22 23 24 25 26 27 28 29]


array([21, 23, 25])

In [111]:
np.all(filedata>50, axis=0)

np.False_

In [113]:
(~(filedata>10) & (filedata <30))

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False])